#pragma once

#include "cosmos/LawGenome.hpp"
#include "cosmos/ScaleLadder.hpp"

#include <string>
#include <vector>

namespace cosmos {

struct Color8 {
    unsigned char r = 200;
    unsigned char g = 200;
    unsigned char b = 255;
};

// A real object archetype. The SI anchor fields are fixed reality; the
// "generated" and "sandbox" fields are filled per-universe by apply_law_genome.
struct UniverseObject {
    std::string id;
    std::string name;
    std::string symbol;
    Scale scale = Scale::ATOMIC;

    // Real-world anchors (SI).
    double rest_mass_kg = 0.0;
    double charge_e = 0.0;   // in elementary charges
    double radius_m = 0.0;
    std::string description;
    std::vector<std::string> constituents; // ids of what it is built from

    // Generated by this universe's law genome.
    double mass_factor = 1.0;    // multiplier on real mass in this universe
    double generated_mass = 0.0; // rest_mass_kg * mass_factor
    double binding = 0.0;        // [0,1] how tightly bound
    double stability = 0.0;      // [0,1] how persistent
    double abundance = 0.0;      // [0,1] how common

    // Dimensionless, well-conditioned parameters for the N-body sandbox.
    double sim_mass = 1.0;
    double sim_charge = 0.0;
    double sim_radius = 1.0;
    Color8 color;
};

// Build the catalog with real anchors only (deterministic, genome-independent).
std::vector<UniverseObject> build_object_catalog();

// Fill the generated + sandbox fields from a specific universe's genome.
// Deterministic: same catalog + same genome -> identical results.
void apply_law_genome(std::vector<UniverseObject>& catalog, const LawGenome& genome);

// Objects belonging to a given tier, in catalog order.
std::vector<const UniverseObject*> objects_for_scale(
    const std::vector<UniverseObject>& catalog, Scale scale);

const UniverseObject* find_object(
    const std::vector<UniverseObject>& catalog, const std::string& id);

} // namespace cosmos
